### ISSUE TITLE
Adm Contingut - Error en guardar un tràmit d'un procediment

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#114]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "PRES_EXTURL": identificador no válido

	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1052)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:537)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:255)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:610)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:253)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:86)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:928)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1136)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3640)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1384)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3730)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3710)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at org.jboss.ironjacamar.jdbcadapters@1.4.11.Final-redhat-00001//org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:537)
	at org.hibernate@5.3.7.Final-redhat-00001//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 176 more
Caused by: Error : 904, Position : 156, Sql = insert into RS2_TRMPRE (PRES_INTPTR, PRES_CODENTI, PRES_FASEPROC, PRES_PLANTI, PRES_TRELEC, PRES_TRPRES, PRES_TRTEL, PRES_INTTID, PRES_INTTPA, PRES_INTTVE, PRES_EXTURL, PRES_CODIGO) values (:1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , :12 ), OriginalSql = insert into RS2_TRMPRE (PRES_INTPTR, PRES_CODENTI, PRES_FASEPROC, PRES_PLANTI, PRES_TRELEC, PRES_TRPRES, PRES_TRTEL, PRES_INTTID, PRES_INTTPA, PRES_INTTVE, PRES_EXTURL, PRES_CODIGO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), Error Msg = ORA-00904: "PRES_EXTURL": identificador no válido

	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 192 more

**Comment by slromero-indra** [comment]
Buenas, hemos revisado el código y el campo fue eliminado en el último tag. Para no tener que volver a crear la base de datos (lo dejamos para la siguiente subida), ejecutad el siguiente comando de base  de datos:

`ALTER TABLE RS2_TRMPRE DROP COLUMN PRES_EXTURL;`

**Comment by bgarcia-dgtic** [comment]
Bon dia, hem executat la sentència però dona error.
`Error que empieza en la línea: 1 del comando :
ALTER TABLE RS2_TRMPRE DROP COLUMN PRES_EXTURL
Informe de error -
Error SQL: ORA-00904: "PRES_EXTURL": identificador no válido
00904. 00000 -  "%s: invalid identifier"
*Cause:    
*Action:`

**Comment by slromero-indra** [comment]
Buenas, podéis generar de nuevo el tag rolsac-2.0-S12_2 y volver a probar?

**Comment by bgarcia-dgtic** [comment]
He tornat a genrar el tag rolsac-2.0-S12_2 i ha funcionat
