### ISSUE TITLE
S15-1 - EVOLUCIÓN UNIDADES ADMINISTRATIVAS: DIVISIÓN

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#120]
Implementar la división en el apartado de evolución de unidades administrativas

**Comment by slromero-indra** [comment]
Generado el tag rolsac-2.0-S15_1 que incluye la evolución división

**Comment by scalafat-dgtic** [comment]
Al crear una UA nueva y hacer las pruebas de #113, al querer dividirla da un NullPointerException

![image](https://github.com/GovernIB/rolsac2/assets/44995350/bd4269cd-d6e4-4942-b052-a32fbb8d6603)

> 2023-11-24 14:37:22,208 DEBUG [es.caib.rolsac2.ejb.interceptor.LoggerInterceptor] (default task-97) UnidadAdministrativaServiceFacadeBean.getNormativaByUa [185, ca]
> 2023-11-24 14:37:22,210 DEBUG [es.caib.rolsac2.ejb.interceptor.LoggerInterceptor] (default task-97) UnidadAdministrativaServiceFacadeBean.getNormativaByUa return([NormativaDTO{id=1073872, numero='null'}, NormativaDTO{id=1450927, numero='null'}, NormativaDTO{id=2164909, numero='null'}, NormativaDTO{id=14068, numero='null'}, NormativaDTO{id=16033, numero='null'}, NormativaDTO{id=1475788, numero='null'}, NormativaDTO{id=1476114, numero='null'}]) in 1 ms
> 2023-11-24 14:37:22,212 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-97) #{dialogUnidadAdministrativa.load}: java.lang.NullPointerException: javax.faces.FacesException: #{dialogUnidadAdministrativa.load}: java.lang.NullPointerException
> 	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:119)
> 
> [...]
> Caused by: javax.faces.el.EvaluationException: java.lang.NullPointerException
> 	at javax.faces.api@2.3.5.SP1-redhat-1//javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
> 	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
> 	... 61 more
> Caused by: java.lang.NullPointerException
> 	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.comun.UtilsArbolTemas.construirArbolDesdeHoja(UtilsArbolTemas.java:39)
> 	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.comun.UtilsArbolTemas.construirArbol(UtilsArbolTemas.java:23)
> 	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogUnidadAdministrativa.construirArbol(DialogUnidadAdministrativa.java:470)
> 	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogUnidadAdministrativa.load(DialogUnidadAdministrativa.java:179)

**Comment by scalafat-dgtic** [comment]
![image](https://github.com/GovernIB/rolsac2/assets/44995350/8aa3a69a-e793-42d8-a065-c6bd14f8cbed)

Apuntamos posibles mejoras:
- Agrupar por acción varios procedimietos/servicios/normativas
- Que aparezcan TODOS los procedimientos, etc. (creo que los procs que están "en modificación" no aparecen)
- Que en la tabla de la imagen aparezca el estado del procedimiento (posibilidad de filtrar/ordenar?)

En consecuencia de este proceso de división, no podemos ver los procedimientos la UA origen deprecada (dividida). Ahora mismo desde Adm.Contenidos no se puede filtrar por UA no visible (ver imagen a continuación) para poder ver los procedimientos de la UA 'no visible' dividida. ¿Cómo lo podríamos arreglar sin hacerlo de este modo? Entendemos que desde Adm-Contenido no se deberían poder ver...

![image](https://github.com/GovernIB/rolsac2/assets/44995350/7341c4a4-7a7c-4126-bd72-f1538914064f)

**Comment by slromero-indra** [comment]
Estamos intentando replicar el error y no somos capaces, nos podéis pasar más información? 

Respecto al botón de crear Unitat Administrativa, era una utilidad extra que se añadió. La idea es que al dividir, pasas toda la información de sus normativas, procedimientos y servicios a otras unidades administrativas (y vimos la posibilidad de crear en tiempo de ejecución una nueva Unidad Administrativa, que se crearía sólo al final de la división). Esa utilidad, también se podría hacer perfectamente, creando antes la unidad administrativa. Si queréis, quitamos la opción de crear una unidad administrativa mientras se crea la división.

Respecto a las mejoras, 

Agrupar por acción varios procedimietos/servicios/normativas. Podemos añadir un check al lado de cada normativa/proc/serv para seleccionar grupalmente. Una vez seleccionado los datos, se seleccionaría en un nuevo desplegable la acción y se asociaría en bloque. Os parece bien?
![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/0c0274be-b606-4bb3-9d17-739bdbbafdc5)

Que aparezcan TODOS los procedimientos, etc. (creo que los procs que están "en modificación" no aparecen). Revisamos esto que comentáis y vemos de que salgan todos. 

Que en la tabla de la imagen aparezca el estado del procedimiento (posibilidad de filtrar/ordenar?)
Si os parece correcto, podemos hacer que sólo al adm. de entidad, le salgan las UAs dadas de baja en el seleccionador de UAs. La idea sería que tuviesen un iconito delante que indicase que está de baja.

**Comment by slromero-indra** [comment]
Respecto a que aparezca el estado + filtro + orden, sólo era viable incluir un icono que indicase la visibilidad del procedimiento/servicio.

Hemos incluido todas las mejoras en el tag 17_1, por favor, cuando podáis lo validáis.
