### ISSUE TITLE
OAE - Poder traducir en campo multietiqueta

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#126]
Se pide que esté disponible la opción de traducción automática en los campos multiidioma.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/618a3971-f77d-4247-b1bc-c2253dc7e057)

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?

**Comment by scalafat-dgtic** [comment]
Veim que les opcions per traduir ja es troben disponibles, però el botó de traduir no funciona (o no fa menció). La funció de traducció des del modal principal del Procediment sí que funciona (està ben configurat)

Per altra banda, segueix havent l'errada que vàrem comentar per telèfon en tancar el modal del Procediment.
2023-12-14 12:31:04,853 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-50) null: java.lang.NullPointerException
	at deployment.rolsac2.ear//es.caib.rolsac2.service.model.NormativaGridDTO.compareTo(NormativaGridDTO.java:352)
	at deployment.rolsac2.ear//es.caib.rolsac2.service.model.ProcedimientoDTO.compareTo(ProcedimientoDTO.java:371)
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogProcedimiento.cerrar(DialogProcedimiento.java:560)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by slromero-indra** [comment]
Se han subido los cambios en el tag rolsac-2.0-S18_1, podéis revisarlo?

**Comment by scalafat-dgtic** [comment]
1. Al intentar traducir, aparece un error de validación, como si esperase un valor

![image](https://github.com/GovernIB/rolsac2/assets/44995350/bf4440b9-438d-465c-92af-c85d3cca50c2)

2. Si ponemos algún valor, al darle a traducir, desaparece el valor en "Text en espanyol"

![image](https://github.com/GovernIB/rolsac2/assets/44995350/e39ad740-8963-48fc-8202-5a8a0b26fa39)

**Comment by scalafat-dgtic** [comment]
Ahora se han hecho pruebas y ha funcionado correctamente
