### ISSUE TITLE
S17-5 Evolución competencias

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#138]

**Comment by scalafat-dgtic** [comment]
He hecho pruebas con varias UAs, asociando (o no) una normativa al principio del proceso de evolución de competencias (y asegurándome de que todos los procedimientos se asociaban a algún lugar, a través del sistema de agrupación) y me salta la alerta de "Almenys té una normativa sense assignar una UA destino" sin poder continuar.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/93dd5ba0-7151-4a6e-8c6b-22ed60bc77a8)

**Comment by scalafat-dgtic** [comment]
També m'ha sorgit un parell de vegades el següent error de "OutOfMemoryError: GC overhead limit exceeded" per si hi ha res que pogueu fer

2024-01-19 09:26:14,213 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-41) /entidades/dialogEvolucionCompetenciaUnidadAdministrativa.xhtml @65,83 flowListener="#{dialogEvolucionCompetenciaUnidadAdministrativa.onFlowProcess}": javax.ejb.EJBException: WFLYEJB0442: Error inesperado: javax.el.ELException: /entidades/dialogEvolucionCompetenciaUnidadAdministrativa.xhtml @65,83 flowListener="#{dialogEvolucionCompetenciaUnidadAdministrativa.onFlowProcess}": javax.ejb.EJBException: WFLYEJB0442: Error inesperado

Caused by: javax.ejb.EJBException: WFLYEJB0442: Error inesperado
	at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:250)


Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.base/java.util.ArrayList.iterator(ArrayList.java:976)
	at org.hibernate@5.3.7.Final-redhat-00001//org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:304)

**Comment by slromero-indra** [comment]
El error de las normativas no se produce en el nuevo tag  [ rolsac-2.0-S19_1 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S19_1). Respecto al error de memoria que comentáis, es un error puntual o general? Con que Unidad Administrativa se produce el error?

**Comment by slromero-indra** [comment]
Hemos comprobado que ya no se produce el error enel estado actual de rolsac2, cuando podáis lo validáis.
