### ISSUE TITLE
NullPointer en prémer opció Editar a un procediment publicat

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#146]
Quan es prem el botó editar en un procediment publicat, dona un NullPointerException

2024-04-05 09:40:50,462 ERROR [org.jboss.as.ejb3.invocation] (default task-77) WFLYEJB0034: Invocación EJB falló en el componente ProcedimientoServiceFacadeBean para el método public abstract java.lang.Long es.caib.rolsac2.service.facade.ProcedimientoServiceFacade.generarModificacion(java.lang.Long,java.lang.String,es.caib.rolsac2.service.model.types.TypePerfiles): javax.ejb.EJBException: java.lang.NullPointerException
	at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)
2024-04-05 09:40:50,500 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-77) java.lang.NullPointerException: javax.ejb.EJBException: java.lang.NullPointerException
	at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)
Caused by: java.lang.NullPointerException at deployment.rolsac2.ear//es.caib.rolsac2.persistence.model.JProcedimientoTramite.merge(JProcedimientoTramite.java:474) at deployment.rolsac2.ear//es.caib.rolsac2.persistence.repository.ProcedimientoRepositoryBean.mergeTramitesProcWF(ProcedimientoRepositoryBean.java:1631)

![nullpointer](https://github.com/GovernIB/rolsac2/assets/44995350/af98ae5b-276f-4272-a3dc-1f7e01598d25)

**Comment by slromero-indra** [comment]
Actualizado el converter de procedimientos para incluir lo necesario para poder realizar una copia en modo edición a partir del dato publicado. Está comiteado en el tag [S21_1 ](https://github.com/GovernIB/rolsac2/commits/rolsac-2.0-S21_1/), cuando podáis lo validáis.
