### ISSUE TITLE
Traspàs BOIB - Error en la cerca per número de registre

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#175]
Quan es fa la cerca d'una normativa del BOIB per núm. registre, es retorna un error:

_2024-07-05 13:02:08,975 ERROR [com.hp.hpl.jena.rdf.model.impl.RDFDefaultErrorHandler] (default task-28) file:///app/jboss-7.2/bin/(line 679 column 31): XML document structures must start and end within the same entity.
2024-07-05 13:02:08,976 ERROR [org.jboss.as.ejb3.invocation] (default task-28) WFLYEJB0034: Invocación EJB falló en el componente BoletinServiceFacadeBean para el método public abstract java.util.List es.caib.rolsac2.service.facade.integracion.BoletinServiceFacade.listar(java.lang.String,java.lang.String,java.lang.String,java.lang.Long): javax.ejb.EJBException: com.hp.hpl.jena.shared.JenaException: org.xml.sax.SAXParseException; systemId: file:///app/jboss-7.2/bin/; lineNumber: 679; columnNumber: 31; XML document structures must start and end within the same entity.
	at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)_ 

_Caused by: com.hp.hpl.jena.shared.JenaException: org.xml.sax.SAXParseException; systemId: file:///app/jboss-7.2/bin/; lineNumber: 679; columnNumber: 31; XML document structures must start and end within the same entity.
	at deployment.rolsac2.ear//com.hp.hpl.jena.rdf.model.impl.RDFDefaultErrorHandler.fatalError(RDFDefaultErrorHandler.java:45)_

_Caused by: org.xml.sax.SAXParseException; systemId: file:///app/jboss-7.2/bin/; lineNumber: 679; columnNumber: 31; XML document structures must start and end within the same entity.__

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/9e010077-a283-4889-8a62-3e2b7d508b9e)

**Comment by slromero-indra** [comment]
Hemos intentado replicar el problema y sólo nos ha aparecido un problema con las fechas que hemos solucionado. En nuestro caso, hemos añadido las opciones que se muestra en la imagen a continuación:
![cap1_boib](https://github.com/user-attachments/assets/f1bd9a04-dd14-4e57-b6cc-cc05e9c4cc3a)


Y al pulsar crear la normativa se puede ver los datos:
![imagen](https://github.com/user-attachments/assets/4afa65a1-b32c-47e5-aa51-857e205910af)


Si os sigue dando error, pasadnos los parámetros que introducís en la búsqueda y el log con completo.

**Comment by scalafat-dgtic** [comment]
Perdonad, tal vez me faltó especificar un poco más.

Al hacer la consulta, **únicamente por Núm. Registro**, es cuando falla. Si lo haces junto a la fecha del boletín, funciona. (En el hipotético caso de que no hubiera solución, que sean obligatorios para evitar el fallo)


_2024-09-13 08:54:28,926 ERROR [org.jboss.as.ejb3.invocation] (default task-10) WFLYEJB0034: Invocación EJB falló en el componente BoletinServiceFacadeBean para el método public abstract java.util.List es.caib.rolsac2.service.facade.integracion.BoletinServiceFacade.listar(java.lang.String,java.lang.String,java.lang.String,java.lang.Long): javax.ejb.EJBException: com.hp.hpl.jena.shared.JenaException: org.xml.sax.SAXParseException; systemId: file:///app/jboss-7.2/bin/; lineNumber: 679; columnNumber: 31; XML document structures must start and end within the same entity.
	at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)_

_Caused by: com.hp.hpl.jena.shared.JenaException: org.xml.sax.SAXParseException; systemId: file:///app/jboss-7.2/bin/; lineNumber: 679; columnNumber: 31; XML document structures must start and end within the same entity.
	at deployment.rolsac2.ear//com.hp.hpl.jena.rdf.model.impl.RDFDefaultErrorHandler.fatalError(RDFDefaultErrorHandler.java:45)_

_Caused by: org.xml.sax.SAXParseException; systemId: file:///app/jboss-7.2/bin/; lineNumber: 679; columnNumber: 31; XML document structures must start and end within the same entity.
	at deployment.rolsac2.ear//org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:201)_

![image](https://github.com/user-attachments/assets/3943a66e-1e07-40b1-9211-62bd058f2f07)

**Comment by scalafat-dgtic** [comment]
Lo miramos

**Comment by slromero-indra** [comment]
Hemos revisado los últimos cambios en BOIB y hemos observado que sigue produciéndose varios errores. Tras realizar varias pruebas, hemos observado que las urls no son las adecuadas: 

![Image](https://github.com/user-attachments/assets/5339dc2b-631d-40ab-98d7-5d9c6d52ec18)

En este caso, se intenta buscar la url https://www.caib.es/eboibfront/ca/2024/12015 y por lo que vemos, no se corresponde. 

Os enviamos más detalles por correo.

**Comment by slromero-indra** [comment]
Hemos actualizado la issue, cuando podáis subís la última versión para poder validar la incidencia.

**Comment by bgarcia-dgtic** [comment]
He fet una prova de cercar només pel número de registre 421016 i no troba res. En cas que sigui obligatori posar la data de butlletí o número de butlletí, s'ha d'informar.

**Comment by slromero-indra** [comment]
Hemos realizado varias pruebas cambiando los parámetros y no vemos el problema. ¿Nos podéis pasar más datos del registro 421016, tenéis el enlace? Puede que haya un problema con dicho dato.

Poniendo fecha 10/04/2025:

![Image](https://github.com/user-attachments/assets/9b54a99f-906c-426d-be5e-050a725680f7)

Poniendo el núm. registro 250133:

![Image](https://github.com/user-attachments/assets/175e4d9e-fdec-4915-82e2-06823759262d)

Poniendo el num. bolletin 044/2025:

![Image](https://github.com/user-attachments/assets/f2c7ca83-e0a8-4a1d-a31f-21d935eba191)

**Comment by bgarcia-dgtic** [comment]
Aquest és l'enllaç https://www.caib.es/eboibfront/eli/es-ib/o/2024/07/02/21/dof/cat/html
És una normativa ELI

**Comment by bgarcia-dgtic** [comment]
He fet una prova només de cercar només per número de registra i permet fer la cerca, encara que es queda pensant sense retornar res. Hauria de mostrar el missatge d'emplenar algun dels dos camps obligatoris.

![Image](https://github.com/user-attachments/assets/a5dbdc91-49db-4fa0-a90e-1ecdc3456b2b)

**Comment by bgarcia-dgtic** [comment]
A Rolsac1 permet cercar per num. de butlletí i data de butlletí al mateix temps. Rolsac2 també haria de poder fer-ho

**Comment by slromero-indra** [comment]
Rolsac1 permite filtrarlo pero prioriza el núm boletín respecto a la fecha:

https://github.com/GovernIB/rolsac/blob/rolsac-1.9/moduls/persistence/src/org/ibit/rol/sac/persistence/eboib/EBoibSearchNormativa.java

![Image](https://github.com/user-attachments/assets/b4f802ff-ca4c-4147-8e6c-3bfe3dc35650)

Esto se debe a que, buscar por ambos valores, no mejora la búsqueda sino puede producir que se obtenga un mal resultado (por ejemplo, si uno de los dos datos es erróneo).

Si busco por núm. boletín, generaría esta url: https://www.caib.es/eboibfront/filtrerss.do?lang=ca&resultados=10&any_ini=2025&any_fin=2025&num_ini=4&num_fin=4
Si busco por fecha generaría esta búsqueda: https://www.caib.es/eboibfront/filtrerss.do?lang=ca&resultados=10&fec_ini=07/01/2025&fec_fin=07/01/2025
Si buscamos por ambos datos: https://www.caib.es/eboibfront/filtrerss.do?lang=ca&resultados=10&any_ini=2025&any_fin=2025&num_ini=4&num_fin=4&fec_ini=07/01/2025&fec_fin=07/01/2025

![Image](https://github.com/user-attachments/assets/1ff464a4-15df-4f9e-8904-5a6708563ba7)

En todos los caso, devuelve el mismo dato. Ahora bien, si uno de los datos es erróneo (por ejemplo, cambiemos la fecha del 07/01/2025 al 08/01/2025) no se devuelve ningún dato : https://www.caib.es/eboibfront/filtrerss.do?lang=ca&resultados=10&any_ini=2025&any_fin=2025&num_ini=4&num_fin=4&fec_ini=08/01/2025&fec_fin=08/01/2025 

Por tanto, teniendo en cuenta todo lo anterior comentado, se puede:
  - Dejarlo como rolsac1, no se avisa al usuario pero se prioriza el núm boletín respecto a la fecha.
  - Permitir introducir ambos valores, como en rolsac1, pero se utilizarían ambos valores en la búsqueda.
  - Dejarlo como está actualmente en rolsac2 para que el usuario priorice sólo uno de los dos valores.

Personalmente, consideramos que la opción actual puede ser más adecuada para el usuario para evitar posible malentendidos pero si os parece más correcta otra opción, la actualizamos.

**Comment by bgarcia-dgtic** [comment]
Hola, 
D'acord, ho deixam així.
