### ISSUE TITLE
Error en la traducció de la normativa

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#176]
Si es vol traduir una normativa de nova creació, en prémer el botó de Traduir, es genera un NullPointerException

2024-07-05 13:35:21,402 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-44) null: java.lang.NullPointerException
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogTraduccion.imprimirLiterales(DialogTraduccion.java:310)
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogTraduccion.load(DialogTraduccion.java:111)

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/c3778a81-d6b4-425e-bb26-f916e6d456c8)

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/de9a9d6d-07fe-44ce-822c-23e57126065d)

**Comment by slromero-indra** [comment]
Se ha actualizado el código para que no se produzca el null pointer, podéis comprobarlo editando y dándole a traducir:

![imagen](https://github.com/user-attachments/assets/9df72416-2fa7-4387-8c3f-199c81d9a128)

**Comment by slromero-indra** [comment]
También funciona con normativas creadas desde 0.

![imagen](https://github.com/user-attachments/assets/0a05ae6b-6a00-415a-8733-f6dd1280a9a3)

**Comment by scalafat-dgtic** [comment]
El error ya no aparece pero faltan campos y aparecen desordenados.

Hay 3 campos marcados como traducibles:

![image](https://github.com/user-attachments/assets/f742485d-12a6-4805-8cbf-bb798105df4a)

- Títol de la normativa (debe salir todo el nombre del campo "Títol de la normativa", no solo "Títol")
- Enllaç a la norma
- Responsable

Ahora solo aparecen "Responsable" i "Títol" y desordenados

![image](https://github.com/user-attachments/assets/bf0ba1ba-8175-421e-8f53-601d7ed071d6)

**Comment by slromero-indra** [comment]
Buenas, pondremos en vez de titol, pondrá títol normativa (y aparecerá el primero).

Respecto al enllaç de la norma, no la añadimos porque al ser una url, creemos que no tiene sentido traducirlo. ¿Queréis agregarlo igualmente?

**Comment by scalafat-dgtic** [comment]
Tiene sentido enlazar normas en ambos idiomas, dado que el BOIB se publica en los idiomas oficiales de la Comunidad. Además, en ROLSAC1 está también de este modo. Entendemos que es un requisito por parte de los gestores.

**Comment by scalafat-dgtic** [comment]
Perdonad, sigue fallando la ventana de traducción al crear normativa **desde el traspaso del BOIB**.

_2024-10-03 14:16:42,372 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-115) null: java.lang.NullPointerException
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogTraduccion.imprimirLiterales(DialogTraduccion.java:310)
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogTraduccion.load(DialogTraduccion.java:111)_

**Comment by slromero-indra** [comment]
Hemos actualizado para evitar el error al hacer un traspaso BOIB, cuando podáis lo validáis.

![traducir_normativas](https://github.com/user-attachments/assets/99206a73-1c5a-433a-85fd-50e78aec262c)

**Comment by scalafat-dgtic** [comment]
Ya se ve el dialog.

No se valida el campo "Enllaç a la norma" al guardar la normativa.
Hay que quitar el asterisco a "Responsable" dado que no es un campo obligatorio.

**Comment by slromero-indra** [comment]
Quitaremos el repsonsable como obligatorio? Que no se valida el campo de enlace, os referís que no valida que sea una url válida?

**Comment by scalafat-dgtic** [comment]
El campo "Enllaç a la norma" ya se valida correctamente. Imagino que se hizo una subida que lo arregló, está OK.
El campo Responsable tiene un asterisco (como si fuera obligatorio) cuando no se valida si se ha rellenado o no (correcto), lo que trae a confusión. Hay que quitar el asterisco.

![image](https://github.com/user-attachments/assets/e500aa2f-80af-4d15-a29e-a176939ab32a)

**Comment by slromero-indra** [comment]
Hemos subido los cambios , cuando podáis lo validáis.

**Comment by bgarcia-dgtic** [comment]
canvis correctes
