### ISSUE TITLE
Implementación Maestro Detalle para Procedimientos y Servicios

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/rolsac2#181]
Implementación Maestro Detalle para Procedimientos y Servicios

**Comment by scalafat-dgtic** [comment]
NOTA: Respecte a l'acceptació o no d'aquesta feina, ho deixarem en mans de la OAE. Mentresant, que es pugui veure sense errades.

Falla en els procediments comuns.

2024-07-10 08:36:23,038 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-6) Error Rendering View[/maestras/viewProcedimientos.xhtml]: javax.el.PropertyNotFoundException: /maestras/detalleProcedimiento.xhtml @102,106 value="#{viewProcedimientos.procedimientoSeleccionado.comunUA.getTraduccion(viewProcedimientos.idioma)}": The class 'es.caib.rolsac2.service.model.ProcedimientoDTO' does not have the property 'comunUA'.
	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:117)

Caused by: javax.el.PropertyNotFoundException: The class 'es.caib.rolsac2.service.model.ProcedimientoDTO' does not have the property 'comunUA'.
	at javax.el.api@1.0.12.Final-redhat-00001//javax.el.BeanELResolver.getBeanProperty(BeanELResolver.java:568)


![Image](https://github.com/GovernIB/rolsac2/assets/44995350/23dca794-b4d5-4b36-8115-8dfd5ebf55c7)

**Comment by slromero-indra** [comment]
Subido el cambio con el error que daba con procedimientos comunes

**Comment by scalafat-dgtic** [comment]
Resuelto por ahora.
Lo dejamos en espera de respuesta por parte de OAE

**Comment by agarcia-dgtic** [comment]
Se pasa a estado Done. En la issue #255 se elimina el Maestro Detalle.
