### ISSUE TITLE
Error en entrar als avisos i alertes

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#189]
En prémer el botó dels avisos i alertes dona el següent error:

2024-08-29 08:58:05,879 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-9) Error Rendering View[/maestras/viewMisAlertas.xhtml]: javax.faces.FacesException: sortBy expects a single or a collection of SortMeta
	at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.component.api.UITable.updateSortByWithUserSortBy(UITable.java:322)

2024-08-29 08:58:05,898 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-9) sortBy expects a single or a collection of SortMeta: javax.faces.FacesException: sortBy expects a single or a collection of SortMeta
	at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.component.api.UITable.updateSortByWithUserSortBy(UITable.java:322)

![image](https://github.com/user-attachments/assets/89d3524d-39cb-4055-ad53-958084ccb4c4)

![image](https://github.com/user-attachments/assets/c899918f-8bb0-4a0f-8b81-0a556bf8adf4)

**Comment by slromero-indra** [comment]
Solucionado el problema con el commit, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Al crear un aviso/alerta y volver a entrar, vuelve a fallar.

2024-09-05 12:11:11,593 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-4) Error Rendering View[/maestras/viewMisAlertas.xhtml]: java.lang.UnsupportedOperationException: DataTable#rowKey must be defined for component formDialog:dataTablePendientes
	at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.component.datatable.DataTable.getRowKey(DataTable.java:574)
	at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.component.datatable.DataTableRenderer.encodeRow(DataTableRenderer.java:1171)

![image](https://github.com/user-attachments/assets/72cfe29d-7119-4272-b514-8a6033a851f7)

**Comment by slromero-indra** [comment]
Solucionado el problema en viewMisAlertas, revisamos lo de la X y os avisamos cuando esté resuelto.

**Comment by scalafat-dgtic** [comment]
OK al viewMisAlertas
Quedamos a la espera de la X

**Comment by slromero-indra** [comment]
Hemos subido los cambios , cuando podáis lo validáis.

**Comment by bgarcia-dgtic** [comment]
funciona correctament
