### ISSUE TITLE
Error si l'usuari no té UA assignada

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#69]
Ens apareix el següent error quan un usuari que no té una unitat administrativa assignada canvia de perfil, encara que tengui el rol corresponent.

![image](https://user-images.githubusercontent.com/44995350/224310659-cf053e1c-a83c-4d51-83fb-332df6103ed0.png)

2023-03-10 08:43:28,005 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-23) null: es.caib.rolsac2.back.exception.NoAutorizadoException: El usuario no tiene permiso para acceder a esta URL con el perfil configurado actualmente.
          at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.AbstractController.permisoAccesoVentana(AbstractController.java:90)
          at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.ViewConfiguracionEntidad.load(ViewConfiguracionEntidad.java:64)
          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2023-03-10 08:43:32,332 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-25) /WEB-INF/includes/header_botonera.xhtml @44,104 listener="#{sessionBean.cambioPerfil(perfil)}": java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0: javax.el.ELException: /WEB-INF/includes/header_botonera.xhtml @44,104 listener="#{sessionBean.cambioPerfil(perfil)}": java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
          at [com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.facelets.el.TagMethodExpression.invoke](mailto:com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.facelets.el.TagMethodExpression.invoke)(TagMethodExpression.java:113)
          at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxBehaviorListenerImpl.java:71)

Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
          at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
          at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
          at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)_

**Comment by scalafat-dgtic** [comment]
Repetir pantalla que aparece en Gestor, cuando el usuario no tiene UA relacionada, en el perfil de Informador (actualmente se muestra en en CC Santa Magdalena Sofía ?)

![image](https://user-images.githubusercontent.com/44995350/228233505-01e85374-d856-4b9c-bd3d-d211b1bb936d.png)

![image](https://user-images.githubusercontent.com/44995350/228233698-1ac36e89-9b22-4884-ba2d-dedde94955d7.png)

**Comment by jcerdar-indra** [comment]
En el tag rolsac2-2.0-S11_1 se modifican los permisos del perfil Informador para que sólo pueda consultar las UAs que tiene asociadas.
