### ISSUE TITLE
S9-1 PROCESO INDEXACIÓN (SEGUNDA FASE)

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#71]
- Se implementará la lógica necesaria para la indexación de servicios, normativas y unidades administrativas.
- Se finalizará la indexación de procedimientos.
- Creación de un proceso de indexación individual (por tipos).
- Adaptaciones y mejoras en la pantalla de consulta de elementos pendientes de indexación

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se completa el proceso de indexación en Solr. Para realizar las pruebas de indexación correspondientes es necesario lo siguiente: 

- Crear el plugin de indexación en la entidad correspondiente:  
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/96287364/230133546-ef3cc080-3e4a-4132-b444-fce44edeccf8.png)

- Crear el proceso automático SOLR_PUNT en el mantenimiento de procesos automáticos. 
![image](https://user-images.githubusercontent.com/96287364/230134340-7f5298a3-a718-4a59-bca8-573c2d107c10.png)

En la pantalla de Reinicio de índices se pueden realizar las pruebas de indexación correspondientes.

**Comment by scalafat-dgtic** [comment]
1. Hemos creado el proceso SOLR_PUNT y le hemos dado a "Indexar normativa" (teníamos solo una) y no se ejecuta por el siguiente error, que se ve en los Logs:

**Indexando en solr el dato:NOR4**
2023-04-19 11:39:23,428 ERROR [stderr] (EJB default - 10) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://<user_filtrado>:<pass_filtrado>@sdesslrlin1.caib.es:8983/solr/**caib**: Expected mime type application/octet-stream but got text/html. <html>
2023-04-19 11:39:23,428 ERROR [stderr] (EJB default - 10) <head>
2023-04-19 11:39:23,428 ERROR [stderr] (EJB default - 10) <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
2023-04-19 11:39:23,428 ERROR [stderr] (EJB default - 10) <title>Error 403 !role</title>
2023-04-19 11:39:23,428 ERROR [stderr] (EJB default - 10) </head>
2023-04-19 11:39:23,428 ERROR [stderr] (EJB default - 10) <body><h2>HTTP ERROR 403</h2>
2023-04-19 11:39:23,429 ERROR [stderr] (EJB default - 10) <p>Problem accessing /solr/caib/update. Reason:
2023-04-19 11:39:23,429 ERROR [stderr] (EJB default - 10) <pre>    !role</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
2023-04-19 11:39:23,429 ERROR [stderr] (EJB default - 10) 
2023-04-19 11:39:23,429 ERROR [stderr] (EJB default - 10) </body>
2023-04-19 11:39:23,429 ERROR [stderr] (EJB default - 10) </html>

------------------------------------------
2023-04-19 11:39:23,477 INFO  [stdout] (EJB default - 10) **Indexando en elastic el dato:NOR4**
2023-04-19 11:41:30,805 ERROR [es.caib.rolsac2.commons.plugins.indexacion.solr.PluginIndexacionSolr] (EJB default - 10) Error indexando contenido: es.caib.solr.api.exception.ExcepcionSolrElasticApi: Producido error en solr y elastic. Solr:org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://<user_filtrado>:<pass_filtrado>@sdesslrlin1.caib.es:8983/solr/caib: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 403 !role</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /solr/caib/update. Reason:
<pre>    !role</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

Elastic:org.apache.http.conn.HttpHostConnectException: Connect to sdeswebgoibray1:21080 [sdeswebgoibray1/10.215.27.4] failed: Expiró el tiempo de conexión (Connection timed out)
	at deployment.rolsac2.ear//es.caib.solr.api.impl.SolrIndexerImpl.indexarContenido(SolrIndexerImpl.java:244)
	at deployment.rolsac2.ear//es.caib.rolsac2.commons.plugins.indexacion.solr.PluginIndexacionSolr.indexarContenido(PluginIndexacionSolr.java:96)

--------------------------

2. Además, una vez finalizado, en Procediments executats se indica que ha fallado pero nada más (no hay trazas de error).

![image](https://user-images.githubusercontent.com/44995350/233040250-6403dcad-4edd-4810-af30-a53f6e1f3e44.png)



3. Revisar literals:
- Cambiar "Fecha fi" por "Data fi"

![image](https://user-images.githubusercontent.com/44995350/233038081-79e7da47-6487-4f5c-b825-011d1637c3e3.png)

- Cambiar "Servicis" por "Serveis". 

![image](https://user-images.githubusercontent.com/44995350/233038313-78215050-d426-4270-9a0a-d246cf04e8f2.png)

![image](https://user-images.githubusercontent.com/44995350/233038399-a7c6f7e3-cd61-4179-bd2d-19ad2aa68aa3.png)

- En el menú, "Reiniciar Índexs" o "Reiniciar **indexis**" lleva a confusión. Cambiarlo por "Indexació" o palabras que no indiquen una acción, sino la entrada a una página nueva.

![image](https://user-images.githubusercontent.com/44995350/233040400-f40cff8c-2e32-4ec2-8dbe-8a227ab043a7.png)

**Comment by slromero-indra** [comment]
Se han solucionado varios problemas de literales en el tag rolsac2-2.0-S9_2 , igualmente estamos revisando porque no se lanza el job que es más importante, cuando tengamos la solución, os avisamos.

**Comment by slromero-indra** [comment]
Buenas, podéis pasarnos la url de configuración del plugin de indexar? Los parámetros deberían ser los mismos (sin user/pass de elastic), el único parámetro que puede cambiar es la url de elastic que apunte a otro sitio aunque debería de terminar en /indexer/solr/

![imagen](https://user-images.githubusercontent.com/17451407/234505982-258f6786-768b-4a38-aabc-43849be11c72.png)

**Comment by scalafat-dgtic** [comment]
Cambiada la property de 'urlElastic' al valor indicado por correo (y que se muestra en la captura). El error sigue siendo el mismo.

![image](https://user-images.githubusercontent.com/44995350/234533096-a68f1cc5-8683-491f-b961-1573de4e39f7.png)

Elastic:org.apache.http.conn.HttpHostConnectException: Connect to sdeswebgoibray1:21080 [sdeswebgoibray1/10.215.27.4] failed: Expiró el tiempo de conexión (Connection timed out)
	at deployment.rolsac2.ear//es.caib.solr.api.impl.SolrIndexerImpl.indexarContenido(SolrIndexerImpl.java:244)

Además, en SOLR, vemos que el valor del esquema está puesto como 'caib' a pelo. Este valor es incorrecto (el valor correcto es 'webcaib') y puede estar causando alguno de los problemas. Debería poder ser modificado via property.

**Comment by slromero-indra** [comment]
Buenas, se han subido cambios de esta issue en el tag rolsac2-2.0-S9_3.

Se ha añadido el parámetro **indexSolr** que en vuestra caso debe ser con el valor **webcaib**

![imagen](https://user-images.githubusercontent.com/17451407/234804539-7ae3949f-b2f6-4395-8511-88c99243abd6.png)


Respecto al problema de conexión con elastic, necesitamos saber si desde el servidor se ve la url http://sdeswebgoibray1:21080/swagger-ui/index.html o cual es la ruta correcta ya que parece que es un problema de visibilidad hacia el restapi.

**Comment by bgarcia-dgtic** [comment]
Hola,
A l'hora de modificar un procediment i tornar-lo a indexar, només s'actualitza a Elastic, a Solr no.
A l'hora d'eliminar un procediment i fer la reindexació, no s'elimina ni a Elastic ni a Solr.

**Comment by slromero-indra** [comment]
En el tag rolsac2-2.0-S10_2 se solucionan los errores comentados además de un error de cast que se producía con servicios.

Respecto a eliminar un procedimiento, hay que entender que una vez publicado, ya no se puede eliminar (sino enviarlo al estado de eliminado).

**Comment by slromero-indra** [comment]
Revisamos los comentarios y vemos de añadirlo en la próxima subida.

**Comment by scalafat-dgtic** [comment]
Buenas, no tenemos noticias sobre el último comentario:
"En la indexación via Elastic, nos ha sorprendido que, estando desindexado solo el procedimiento de muestra (el servicio y la normativa estaban indexados), al darle a "Indexar pendents" nos ha indexado el procedimiento y nos ha desindexado el servicio.

¿Lo podéis mirar?

image

Logs del último proceso 19/06/2023 a las 13:37h que se ve en la captura anterior:

image

PD1: Como mejoras, estaría bien que en una columna aparte o dentro de la columa de Resultat apareciese donde se ha indexado exactamente. (Sabemos que a futuro indexaremos solo en un sitio, pero durante el proceso nos sería útil poder verlo)

PD1bis: También que aparezca en la tabla el código de cada proceso; así al mostrar los logs sabemos qué proceso corresponde. P.ej: el código 32 que aparece en esta última captura de pantalla no se sabe a qué proceso se refiere

PD2: Estaría bien, también, que en la ventana de los logs, entre entidades a indexar, hubiese una línea separatoria. Se hace difícil a veces ver los resultados de indexación de cada entidad.

PD3: La paginación de la tabla de procesos de indexación (primera captura) no funciona. Ahora mismo, no sabemos cuantos procesos hemos lanzado y no podemos pasar a la segunda página de la tabla (para mostraros un ejemplo del PD2)
""

**Comment by slromero-indra** [comment]
Revisamos los problemas que habláis indexando los datos. 

Respecto a las mejoras que comentáis (PD1, PD1bis, PD2, PD3), veremos de añadirlas en la próxima subida.

**Comment by slromero-indra** [comment]
Se han subido los cambios al tag [ rolsac-2.0-S19_1 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S19_1).

Los cambios introducidos son:
-	Solucionado el error en paginación.
-	Añadido el código y la opción visual de ver si está ejecutado en modo activo solr y elastic.
-	Solucionado un error que si se seleccionaba un elemento de la lista, daba un error (se ha quitado la posibilidad de elección).
-	Mejorado la auditación cuando se indexa, cada 5 elementos, se actualiza para que se vea si está indexando correctamente. 
-	Controlado un posible bug al intentar indexar un procedimiento que ya no existe (eso se puede comprobar si se crear un procedimiento y, antes de enviarlo a indexar, se realiza una migración borrando datos).

En los comentarios, habláis de dos imágenes pero por alguna razón, en github ya no se ven. 
Tenemos las siguientes dudas:

 Respecto al siguiente comentario:
`PD1: Como mejoras, estaría bien que en una columna aparte o dentro de la columa de Resultat apareciese donde se ha indexado exactamente. (Sabemos que a futuro indexaremos solo en un sitio, pero durante el proceso nos sería útil poder verlo)`
¿Queréis que salga un total de datos indexados en solr y elastic?

Respecto a:
`PD2: Estaría bien, también, que en la ventana de los logs, entre entidades a indexar, hubiese una línea separatoria. Se hace difícil a veces ver los resultados de indexación de cada entidad.
`
Os referís a que en primera línea se vea la entidad que lo ejecuta? Normalmente todas las indexaciones menos la de pendientes se ejecuta a nivel de una entidad. Queréis que indique siempre en la primera línea la entidad responsable? (en caso de ser la de pendientes, se podría ver de indicar o separar por entidades)

**Comment by scalafat-dgtic** [comment]
Respecto a las imágenes que no se ven, el último comentario (del 25/10) fue un copy-paste del comentario del 19/06. De ahí que no se vean los imágenes (se ven en el comentario de junio).

OK a pregunta sobre PD1
Sobre pregunta de PD2, creo que ahora ya se ve mejor (no había saltos de línea entre cada entidad indexada y esto dificultaba mucho su seguimiento), lo podemos dejar así.

**Comment by slromero-indra** [comment]
Faltaba incorporar un total de datos indexados en solr y elastics. Hemos comiteado los cambios para resolver la issue, cuando podáis lo validáis.
