### ISSUE TITLE
Error en crear Normatives

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#83]
En voler crear una normativa, falla. Algun problema amb els scripts?

2023-04-19 08:34:38,806 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-14) #{dialogNormativa.guardar}: es.caib.rolsac2.service.exception.ServiceException: Error interno. Consulte con el administrador: javax.faces.FacesException: #{dialogNormativa.guardar}: es.caib.rolsac2.service.exception.ServiceException: Error interno. Consulte con el administrador
	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:119)

Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: la tabla o vista no existe

Caused by: Error : 942, Position : 56, Sql = select count(jindexacio0_.ISOL_CODIGO) as col_0_0_ from RS2_IDSOLR jindexacio0_ where jindexacio0_.ISOL_CODENT=:1  and (jindexacio0_.ISOL_TIPO like :2 ) and jindexacio0_.ISOL_CODELE=:3 , OriginalSql = select count(jindexacio0_.ISOL_CODIGO) as col_0_0_ from RS2_IDSOLR jindexacio0_ where jindexacio0_.ISOL_CODENT=? and (jindexacio0_.ISOL_TIPO like ?) and jindexacio0_.ISOL_CODELE=?, Error Msg = ORA-00942: la tabla o vista no existe

	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)

![image](https://user-images.githubusercontent.com/44995350/232987582-36dd2ca1-c2f2-42f7-9186-4c63a8deac2a.png)

**Comment by slromero-indra** [comment]
Buenas, parece ser que faltan los grants y los sinónimos a las nuevas tablas de SOLR y SIA.

Se tiene que ejecutar las siguientes instrucciones grants desde rolsac2 hacia el usuario www_rolsac2:
 
```
GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "RS2_IDSOLR" TO www_rolsac2;
GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "RS2_IDSIA" TO www_rolsac2;
GRANT SELECT ON "RS2_IDSOLR_SEQ" TO WWW_ROLSAC2;
GRANT SELECT ON "RS2_IDSIA_SEQ" TO WWW_ROLSAC2;
```


Se tiene que ejecutar los siguientes instrucciones synonyms en el usuario www_rolsac2:
```

CREATE SYNONYM WWW_ROLSAC2.RS2_IDSOLR FOR "RS2_IDSOLR";
CREATE SYNONYM WWW_ROLSAC2.RS2_IDSIA FOR "RS2_IDSIA";
```

Actualizamos el synonym.sql y grants.sql. Por favor, cuando ejecutéis las sql de antes, nos confirmáis si se soluciona el error con los grants.

**Comment by scalafat-dgtic** [comment]
Ok, faltaba eso. Ya funciona
